package rules
 
import model.Product
import java.util.Date

global readDroolsReturnedValue.DroolsResultContainer resultContainer_defined_in_drl;

rule "Offer for Diamond"
	when 
		productObject: Product()
	then
		productObject.setDiscount(150000);
//		insert(new Date());
		resultContainer_defined_in_drl.putValueByKey("k1", productObject);
		resultContainer_defined_in_drl.putValueByKey("k2", new Date());
	end